# Generated by Django 2.2 on 2020-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
