# Generated by Django 2.2 on 2020-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200722_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
